### ISSUE TITLE
Monitor etcd for k0s

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/flux-cluster-template#1147]
Looks like it requires grabbing the content of these files and applying a secret for kube-prometheus-stack can use:

```curl --cacert /var/lib/k0s/pki/etcd/ca.crt --cert /var/lib/k0s/pki/etcd/server.crt --key /var/lib/k0s/pki/etcd/server.key https://localhost:2379/metrics```

**Comment by onedr0p** [comment]
cc @brunnels

**Comment by onedr0p** [comment]
@brunnels  I wonder if we could use a hook to put these into a secret in the cluster

```yaml
hooks:
  apply:
    after:
      - sudo k0s kubectl create namespace observability > /dev/null 2>&1 || true
      - sudo k0s kubectl create secret generic etcd-certs --from-file=cacert=/var/lib/k0s/pki/etcd/ca.crt --from-file=cert=/var/lib/k0s/pki/etcd/server.crt --from-file=key=/var/lib/k0s/pki/etcd/server.key  > /dev/null 2>&1 || true
```
