### ISSUE TITLE
Make the config file more structured

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/flux-cluster-template#1249]
There is a lot of flat vars that could be expanded into more structure keys. I would also like to utilize Pydantic to generate a JSON schema for validation.

```yaml
---
# (Required) Distribution can either be k3s, k0s, or talos
kubernetes_distribution: ""

# (Required) IANA formatted timezone (e.g. America/New_York)
timezone: ""

# (Required) Use only 1, 3 or more ODD number of controller nodes, recommended is 3
node_controllers: []
  # - name: ""           # Name of the node (must match [a-z0-9-\.]+)
  #   address: ""        # IP address of the node
  #   ssh:
  #     username: ""     # (Required: k3s/k0s) SSH username of the node
  #   talos:
  #     disk_device: ""  # (Required: Talos) Device Path or Serial number of Disk for this node

# (Optional) Workers are not required for a cluster to function
node_workers: []
  # - name: ""           # Name of the node (must match [a-z0-9-\.]+)
  #   address: ""        # IP address of the node
  #   ssh:
  #     username: ""     # (Required: k3s/k0s) SSH username of the node
  #   talos:
  #     disk_device: ""  # (Required: Talos) Device Path or Serial number of Disk for this node

# (Required) CIDR your nodes are on (e.g. 192.168.1.0/24)
node_network: ""

# (Required) DNS options
node_dns:
  # (Optional) The DNS search domain to use for the nodes.
  # Leave this option blank to avoid DNS issues inside the cluster.
  search_domain: ""
  # (Required) The DNS server to use for the cluster, this can be an existing
  #   local DNS server or a public one
  # If using a local DNS server make sure it meets the following requirements:
  #   1. your nodes can reach it
  #   2. it is configured to forward requests to a public DNS server
  #   3. you are not force redirecting DNS requests to it - this will break cert generation over DNS01
  servers: []

# (Required) The pod CIDR for the cluster, this must NOT overlap with any
#   existing networks. If you want to use IPv6 check the advanced flags below
cluster_pod_network: 10.69.0.0/16

# (Required) The service CIDR for the cluster, this must NOT overlap with any
#   existing networks. If you want to use IPv6 check the advanced flags below
cluster_service_network: 10.96.0.0/16

# (Required) The IP address of the Kube API, choose an available IP in
#   your nodes network that is NOT being used. This is announced over L2.
cluster_endpoint_vip: ""

# (Optional) Add additional SANs to the Kube API cert, this is useful
#   if you want to call the Kube API by hostname rather than IP
cluster_tls_sans: []

# (Required) Flux details
# IMPORTANT: All options are ignored if flux is disabled and no resources
#   outside Cilium and kube-vip (k0s/k3s) will be deployed to your cluster.
flux:
  # (Required) Disable to use a different tool (e.g. kubectl, Argo, Kluctl)
  enabled: true
  # (Required) Github repository URL (for private repos use the ssh:// URL)
  github_address: ""
  # (Required) Github repository branch
  github_branch: main
  # (Optional) Flux webhook token for Github push-based sync (openssl rand -hex 12)
  github_webhook_token:
  # (Required) Age Public Key (e.g. age15uzrw396e67z9wdzsxzdk7ka0g2gr3l460e0slaea563zll3hdfqwqxdta)
  sops_age_public_key: ""

# (Required) Cloudflare details - Cloudflare is used for DNS, TLS certificates and tunneling.
# IMPORTANT: All options are ignored if cloudflare is disabled and no resources
#   outside a bare Flux setup will be deployed to your cluster if Flux is enabled.
cloudflare:
  # (Required) Disable to use a different DNS provider
  enabled: true
  # (Required) Cloudflare Account ID
  # Ref: https://developers.cloudflare.com/fundamentals/setup/find-account-and-zone-ids/
  account_id: ""
  # (Required) Cloudflare Domain
  domain: ""
  # (Required) Cloudflare API Token (NOT API Key)
  token: ""
  # (Required) Email you want to be associated with the ACME account (used for TLS certs via letsencrypt.org)
  acme_email: ""
  # (Required) Use the ACME production server when requesting the wildcard certificate.
  #   By default the ACME staging server is used. This is to prevent being rate-limited.
  #   Update this option to `true` when you have verified the staging certificate
  #   works and then re-run `task configure` and push your changes to Github.
  acme_production: false
  # (Required) Cloudflared Tunnel ID (cat ~/.cloudflared/*.json | jq -r .TunnelID)
  tunnel_id: ""
  # (Required) Cloudflared Tunnel Secret (cat ~/.cloudflared/*.json | jq -r .TunnelSecret)
  tunnel_secret: ""
  # (Required) Provide WAN access to the cluster ingresses for external ingress classes
  # The Load balancer IP for external ingress, choose an available IP
  #   in your nodes network that is NOT being used. This is announced over L2.
  # Ref: https://github.com/kubernetes/ingress-nginx
  tunnel_ingress_vip: ""
  # (Required) Provide LAN access to the cluster ingresses for internal ingress classes
  # The Load balancer IP for internal ingress, choose an available IP
  #   in your nodes network that is NOT being used. This is announced over L2.
  # Ref: https://github.com/kubernetes/ingress-nginx
  ingress_vip: ""
  # (Required) Gateway is used for providing DNS to your cluster on LAN
  # The Load balancer IP for k8s_gateway, choose an available IP
  #   in your nodes network that is NOT being used. This is announced over L2.
  # Ref: https://github.com/ori-edge/k8s_gateway
  gateway_vip: ""

# (Optional) Feature gates are used to enable experimental features
feature_gates:
  # Enable Dual Stack IPv4 first
  # IMPORTANT: I am looking for people to help maintain IPv6 support since I cannot test it.
  #   Ref: https://github.com/onedr0p/flux-cluster-template/issues/1148
  # Keep in mind that Cilium does not currently support IPv6 L2 announcements.
  # Make sure you set cluster.pod_cidr and cluster.service_cidr
  #   to a valid dual stack CIDRs, e.g. "10.42.0.0/16,fd00:10:244::/64"
  dual_stack_ipv4_first: false
```
