### ISSUE TITLE
Sops decrypt: can't find file /home/<user>/.config/sops/age/keys.txt

### ISSUE THREAD

**Issue by Moortu** [onedr0p/flux-cluster-template#1262]
main-pc OS: EndeavourOS (archlinux)
nodes OS: rocky-linux 9.3

When I run go-task flux:bootstrap, it fails with "can't find file ~/.config/sops/age/keys.txt" 
this is because in the Sops.taskfile.yaml it makes the age.keys file **age-keygen --output {{.SOPS_AGE_FILE}}**
but in the flux.taskfule.yaml it doesn't refer to that file  **sops --decrypt {{.CLUSTER_SECRET_SOPS_FILE}}**  
so it will look in the default folder/file

I solved this by  **cp age.keys ~/.config/sops/age/keys.txt**

PS: everything works on rocky-linux 9.3

**Comment by onedr0p** [comment]
Weird, direnv should have exported `SOPS_AGE_KEY_FILE` for you. I did notice a naming discrepancy in the taskfile `SOPS_AGE_FILE` and will update that.

**Comment by onedr0p** [comment]
Thanks for the feedback, not sure if maybe your env wasn't exported correctly since I just tested this without a file in `~/.config/sops/age/keys.txt` and it worked.

Anyways I update a few things including the var name in the taskfile here https://github.com/onedr0p/flux-cluster-template/pull/1263 Going to go ahead and close this issue. Thanks again!

**Comment by pabloaugusto** [comment]
I had same issue here @onedr0p while using vscode extension SOPS Edit Easy
This extension dont support `SOPS_AGE_KEY_FILE`
https://marketplace.visualstudio.com/items?itemName=ShipitSmarter.sops-edit

As an workaround i did:
- edit `.taskfiles/Sops/Taskfile.yam` and add the following code to `sops:age-keygen` task

```yaml
tasks:
  age-keygen:
    desc: Initialize Age Key for Sops
    cmds:
      - age-keygen --output {{.AGE_FILE}}
      - mkdir -p $PWD/.config/sops/age # NEWCODE
      - ln -f {{.AGE_FILE}} $PWD/.config/sops/age/keys.txt # NEWCODE
    status: ["test -f {{.AGE_FILE}}"]
```
