### ISSUE TITLE
Logic Error in configure script when creating Host SOPS

### ISSUE THREAD

**Issue by PrymalInstynct** [onedr0p/flux-cluster-template#499]
# Issue

When running the `task configure` command the `generate_ansible_host_secrets` function will only produce a secrets file named with the `BOOTSTRAP_ANSIBLE_DEFAULT_NODE_HOSTNAME_PREFIX` variable.

# Expected outcome
SOPS files created with the correct hostnames for the master and worker hosts in the host_vars folder

# Details

**.config.env** (pertinent details from .config.env file)
```
export BOOTSTRAP_ANSIBLE_DEFAULT_CONTROL_NODE_HOSTNAME_PREFIX="k8s-control-dev-"
export BOOTSTRAP_ANSIBLE_DEFAULT_NODE_HOSTNAME_PREFIX="k8s-worker-dev-"

export BOOTSTRAP_ANSIBLE_HOSTNAME_0=""
export BOOTSTRAP_ANSIBLE_HOSTNAME_1=""
export BOOTSTRAP_ANSIBLE_HOSTNAME_2=""
export BOOTSTRAP_ANSIBLE_HOSTNAME_3=""
export BOOTSTRAP_ANSIBLE_HOSTNAME_4=""
```

**configure** (snip of code causing issues)
```bash
generate_ansible_host_secrets() {
    local node_id=
    local node_username=
    local node_password=
    local node_hostname=
    default_control_node_prefix=${BOOTSTRAP_ANSIBLE_DEFAULT_CONTROL_NODE_HOSTNAME_PREFIX:-k8s-}
    default_worker_node_prefix=${BOOTSTRAP_ANSIBLE_DEFAULT_NODE_HOSTNAME_PREFIX:-k8s-}
    for var in "${!BOOTSTRAP_ANSIBLE_HOST_ADDR_@}"; do
        node_id=$(echo "${var}" | awk -F"_" '{print $5}')
        if [[ "${!node_control}" == "true" ]]; then
            node_hostname="BOOTSTRAP_ANSIBLE_HOSTNAME_${node_id}"
            host_key="${!node_hostname:-${default_control_node_prefix}}"
            if [ "${host_key}" == "${default_control_node_prefix}" ]; then
                node_hostname=${default_control_node_prefix}${node_id}
            else
                node_hostname=${!node_hostname}
            fi
        else
            node_hostname="BOOTSTRAP_ANSIBLE_HOSTNAME_${node_id}"
            host_key="${!node_hostname:-${default_worker_node_prefix}}"
            if [ "${host_key}" == "${default_worker_node_prefix}" ]; then
                node_hostname=${default_worker_node_prefix}${node_id}
            else
                node_hostname=${!node_hostname}
            fi
        fi
        {
            node_username="BOOTSTRAP_ANSIBLE_SSH_USERNAME_${node_id}"
            node_password="BOOTSTRAP_ANSIBLE_SUDO_PASSWORD_${node_id}"
            printf "kind: Secret\n"
            printf "ansible_user: %s\n" "${!node_username}"
            printf "ansible_become_pass: %s\n" "${!node_password}"
        } > "${PROJECT_DIR}/provision/ansible/inventory/host_vars/${node_hostname}.sops.yml"
        sops --encrypt --in-place "${PROJECT_DIR}/provision/ansible/inventory/host_vars/${node_hostname}.sops.yml"
    done
}
```

# Observation
If I change line 410 of the script to `if [[ "${!node_control}" == "false" ]]; then` it will use the `BOOTSTRAP_ANSIBLE_DEFAULT_CONTROL_NODE_HOSTNAME_PREFIX` variable instead of the `BOOTSTRAP_ANSIBLE_DEFAULT_NODE_HOSTNAME_PREFIX` variable

**Comment by onedr0p** [comment]
Feel free to open a PR, I would much appreciate the help. Thanks!

**Comment by PrymalInstynct** [comment]
I would if was a better with bash script. I looked at the code but didn't see anything obvious.

Thanks

**Comment by onedr0p** [comment]
I tested this out and got the expected result:

```sh
export BOOTSTRAP_ANSIBLE_DEFAULT_CONTROL_NODE_HOSTNAME_PREFIX="k8s-control-"
export BOOTSTRAP_ANSIBLE_DEFAULT_NODE_HOSTNAME_PREFIX="k8s-worker-"

export BOOTSTRAP_ANSIBLE_HOST_ADDR_0="0.0.0.0"
export BOOTSTRAP_ANSIBLE_SSH_USERNAME_0="fake"
export BOOTSTRAP_ANSIBLE_SUDO_PASSWORD_0="fake"
export BOOTSTRAP_ANSIBLE_CONTROL_NODE_0="true"
export BOOTSTRAP_ANSIBLE_HOSTNAME_0=""

export BOOTSTRAP_ANSIBLE_HOST_ADDR_1="1.0.0.0"
export BOOTSTRAP_ANSIBLE_SSH_USERNAME_1="fake"
export BOOTSTRAP_ANSIBLE_SUDO_PASSWORD_1="fake"
export BOOTSTRAP_ANSIBLE_CONTROL_NODE_1=""
export BOOTSTRAP_ANSIBLE_HOSTNAME_1=""
```

```sh
❯ tree provision/ansible/inventory/
├── group_vars
│   ├── kubernetes
│   │   ├── k3s.yml
│   │   ├── kube-vip.yml
│   │   └── os.yml
│   ├── master
│   │   └── k3s.yml
│   └── worker
│       └── k3s.yml
├── hosts.yml
└── host_vars
    ├── k8s-worker-0.sops.yml
    └── k8s-worker-1.sops.yml
```

**Comment by PrymalInstynct** [comment]
Sorry missed providing a relevant detail

I am creating 3 control nodes and 2 worker nodes. All 5 of the sops files get the same hostname prefix regardless of if `BOOTSTRAP_ANSIBLE_CONTROL_NODE` is set to true or false

```
provision/ansible/inventory/
├── group_vars
│   ├── kubernetes
│   │   ├── k3s.yml
│   │   ├── kube-vip.yml
│   │   └── os.yml
│   ├── master
│   │   └── k3s.yml
│   └── worker
│       └── k3s.yml
├── host_vars
│   ├── k8s-worker-dev-0.sops.yml
│   ├── k8s-worker-dev-1.sops.yml
│   ├── k8s-worker-dev-2.sops.yml
│   ├── k8s-worker-dev-3.sops.yml
│   └── k8s-worker-dev-4.sops.yml
└── hosts.yml
```
 I would expect 0-2 to be control and 3-4 to be worker

**Comment by onedr0p** [comment]
Oh I see that now on my end too, sorry. Let me try to fix that. For now you can just alter the files manually

**Comment by PrymalInstynct** [comment]
yep, that is what I did.

Thanks!

FYI, I am about to open another issue or maybe a PR if I can figure it out. The `Packages | Install required packages` task in cluster-prepare.yml is yelling about not being able to converting a dict to a list.

```
fatal: [k8s-worker-dev-3]: FAILED! => changed=false 
  msg: 'argument ''name'' is of type <class ''dict''> and we were unable to convert to list: <class ''dict''> cannot be converted to a list'
```

**Comment by onedr0p** [comment]
Hm not of the top of my head on that one, are you on the latest version of ansible?

**Comment by PrymalInstynct** [comment]
```
ansible [core 2.13.5]
  config file = /home/zimmermanc/Projects/k8s-dev-cluster/ansible.cfg
  configured module search path = ['/home/zimmermanc/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/linuxbrew/.linuxbrew/Cellar/ansible/6.5.0/libexec/lib/python3.10/site-packages/ansible
  ansible collection location = /home/zimmermanc/.ansible/collections
  executable location = /home/linuxbrew/.linuxbrew/bin/ansible
  python version = 3.10.8 (main, Oct 11 2022, 11:35:05) [GCC 11.2.0]
  jinja version = 3.1.2
  libyaml = True
```

**Comment by onedr0p** [comment]
Fix for the issue on control nodes not being named properly done in https://github.com/onedr0p/flux-cluster-template/commit/4cf34653cbf6a1f70c0f3a27273902745506c147

**Comment by onedr0p** [comment]
Not sure about the issue with `Packages | Install required packages` task, it should be pulling from the `packages` var in `provision/ansible/inventory/group_vars/kubernetes/os.yml`

**Comment by PrymalInstynct** [comment]
yeah, I am not sure either, but it is something with the group_vars/kubernetes/os.yml file, because I just changed the task to look like this and it works file.

```yaml
        - name: Packages | Install required packages
          ansible.builtin.dnf:
            name: "{{ packages }}"
            state: present
            update_cache: true
          vars:
            packages:
            - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
            - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
            - dnf-automatic
            - dnf-plugin-system-upgrade
            - dnf-utils
            - hdparm
            - htop
            - intel-gpu-tools
            - ipvsadm
            - lm_sensors
            - nano
            - nvme-cli
            - socat
            - python3-libselinux
```

**Comment by PrymalInstynct** [comment]
ok got it,

At the top of the Packages block I added an `include_vars` task and it works.

```yaml
    - name: Packages
      block:
        - name: Packages | Include package variables
          ansible.builtin.include_vars:
            dir: ../inventory/group_vars/kubernetes
```
