### ISSUE TITLE
Task Verify bootstrap node names fails

### ISSUE THREAD

**Issue by mrueg** [onedr0p/flux-cluster-template#909]
```
TASK [Verify bootstrap node names are valid] **********************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "Unexpected templating type error occurred on ({{ bootstrap_nodes.master + bootstrap_nodes.worker | default([]) }}): can only concatenate list (not \"NoneType\") to list. can only concatenate list (not \"NoneType\") to list"}
```

I don't have any worker nodes defined but only a single master.

**Comment by onedr0p** [comment]
I cannot replicate this with the follow config values:

```yaml
bootstrap_nodes:
  master:
    - name: k8s-0
      address: 192.168.42.10
      username: root
      password: password
    - name: k8s-1
      address: 192.168.42.11
      username: root
      password: password
    - name: k8s-2
      address: 192.168.42.12
      username: root
      password: password
  # worker: []
```

or

```yaml
bootstrap_nodes:
  master:
    - name: k8s-0
      address: 192.168.42.10
      username: root
      password: password
    - name: k8s-1
      address: 192.168.42.11
      username: root
      password: password
    - name: k8s-2
      address: 192.168.42.12
      username: root
      password: password
  worker: []
```

What do your values look like?

**Comment by mrueg** [comment]
This does not work:
```
bootstrap_nodes:
  # Use only 1, 3 or more odd master nodes, recommended is 3
  master:
      - name: host
        address: adress
        username: user
        password: password
   worker: 
   # add workers here
```

This does work:
```
bootstrap_nodes:
  # Use only 1, 3 or more odd master nodes, recommended is 3
  master:
      - name: host
        address: adress
        username: user
        password: password
   worker: 
  # see the empty list
  []
```
